{% set version = '0.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-toastui
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/toastui_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/toastui/toastui_{{ version }}.tar.gz
  sha256: b79b8a71e09f4f0276ab8268430d1daa532b119532b1fd84a8d07ebd991ad4d4

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-magrittr
    - r-phosphoricons
    - r-rlang
    - r-shiny >=1.1.0
    - r-shinywidgets
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-magrittr
    - r-phosphoricons
    - r-rlang
    - r-shiny >=1.1.0
    - r-shinywidgets

test:
  commands:
    - $R -e "library('toastui')"           # [not win]
    - "\"%R%\" -e \"library('toastui')\""  # [win]

about:
  home: https://dreamrs.github.io/toastui/
  license: MIT
  summary: Create interactive tables, calendars and charts with 'TOAST UI' <https://ui.toast.com/>
    libraries to integrate in 'shiny' applications or 'rmarkdown' 'HTML' documents.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
